# Generated by Django 5.0.3 on 2024-03-15 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_header'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Header',
            new_name='Head_info',
        ),
    ]
